DATA-SCIENCE -Activity monitoring - Building a complete pipeline for sensor-based activity recognition 


TEAM MEMBERS--BITF20M013-MUHAMMAD WAQAS-UD-DIN, BITF20M032-JAMSHAID MEHMOOD, BITF20M018-KABEER ALI , BITF20M031-MUHAMMAD HAMZA FAROOQI

Step: Import libraries and Loading the Data (Training and Testing)

In [85]:
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
path = "C:\\Users\\lenovo\\DS_PROJECT\\"
train_accelerometer = np.load(path+"training\\trainAccelerometer.npy")
train_msgyroscope = np.load(path+"training\\trainMSGyroscope.npy")
train_msaccelerometer = np.load(path+"training\\trainMSAccelerometer.npy")
train_magnetometer = np.load(path+"training\\trainMagnetometer.npy")
train_linearacceleration = np.load(path+"training\\trainLinearAcceleration.npy")
train_jinsgyroscope = np.load(path+"training\\trainJinsGyroscope.npy")
train_jinsaccelerometer = np.load(path+"training\\trainJinsAccelerometer.npy")
train_gyroscope = np.load(path+"training\\trainGyroscope.npy")
train_gravity = np.load(path+"training\\trainGravity.npy")
train_labels = np.load(path+"training\\trainLabels.npy")

In [35]:
path = "C:\\Users\\lenovo\\DS_PROJECT\\"
test_accelerometer = np.load(path+"testing/testAccelerometer.npy")
test_msgyroscope = np.load(path+"testing/testMSGyroscope.npy")
test_msaccelerometer = np.load(path+"testing/testMSAccelerometer.npy")
test_magnetometer = np.load(path+"testing/testMagnetometer.npy")
test_linearacceleration = np.load(path+"testing/testLinearAcceleration.npy")
test_jinsgyroscope = np.load(path+"testing/testJinsGyroscope.npy")
test_jinsaccelerometer = np.load(path+"testing/testJinsAccelerometer.npy")
test_gyroscope = np.load(path+"testing/testGyroscope.npy")
test_gravity = np.load(path+"testing/testGravity.npy")
test_labels = np.load(path+"testing/testLabels.npy")

PRINTING THE LABLES.

In [40]:
#Training
print(train_labels.shape)
print(train_linearacceleration.shape)
print(train_jinsgyroscope.shape)
print(train_jinsaccelerometer.shape)
print(train_gravity.shape)
print(train_msaccelerometer.shape)
print(train_msgyroscope.shape)
print(train_gyroscope.shape)
print(train_magnetometer.shape)
print(train_accelerometer.shape)
#TESTING
print(test_labels.shape)
print(test_linearacceleration.shape)
print(test_jinsgyroscope.shape)
print(test_jinsaccelerometer.shape)
print(test_gravity.shape)
print(test_msaccelerometer.shape)
print(test_msgyroscope.shape)
print(test_gyroscope.shape)
print(test_magnetometer.shape)
print(test_accelerometer.shape)

(2284,)
(2284, 800, 3)
(2284, 80, 3)
(2284, 80, 3)
(2284, 800, 3)
(2284, 268, 3)
(2284, 268, 3)
(2284, 800, 3)
(2284, 200, 3)
(2284, 800, 3)
(2288,)
(2288, 800, 3)
(2288, 80, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 268, 3)
(2288, 268, 3)
(2288, 800, 3)
(2288, 200, 3)
(2288, 800, 3)


Printing The Lables from Testing and Training Data

In [41]:
print(max(train_labels))   
print(max(test_labels))   

54
54


OBSERVING THE LABLES BY DRWAING SHAPES:

In [42]:
train_labels_0 = train_labels[train_labels==0]
print(train_labels_0.shape)

train_labels_1 = train_labels[train_labels==1]
print(train_labels_1.shape)

train_labels_2 = train_labels[train_labels==2]
print(train_labels_2.shape)

train_labels_3 = train_labels[train_labels==3]
print(train_labels_3.shape)


(41,)
(42,)
(43,)
(42,)


STEP: PERFORMING THE NORMALIZATION

In [43]:
def normalize(data_set):
    data_set = data_set.astype('float32')
    for k in range(data_set.shape[0]):
      for i in range(3):
        mean = np.mean(data_set[k,:,i])
        std = np.std(data_set[k,:,i])
        data_set[k,:,i] = (data_set[k,:,i] - mean) / (std + 1e-7)
    return data_set

In [44]:
#Lets obsevsrve the Traing Data Files like one of these Files is.
print(train_msgyroscope)
print(train_msgyroscope.shape)

[[[ 1.55487812e+00  2.80487823e+00  2.50000000e+00]
  [ 1.58536589e+00  2.83536601e+00  2.59146357e+00]
  [ 1.73780489e+00  3.07926846e+00  2.46951222e+00]
  ...
  [ 5.61280518e+01 -3.99390244e+00  1.49695129e+01]
  [ 4.80182953e+01 -7.40853691e+00  3.09451218e+01]
  [ 3.96341476e+01 -9.54268360e+00  4.79878044e+01]]

 [[ 7.01219559e-01  1.15853667e+00 -1.06707323e+00]
  [ 1.00609756e+00  1.28048778e+00 -1.43292689e+00]
  [ 9.45122004e-01  1.31097567e+00 -1.49390244e+00]
  ...
  [ 3.53658562e+01  2.61280499e+01  1.17926834e+02]
  [ 2.72865868e+01  2.63109760e+01  1.16554878e+02]
  [ 8.53658581e+00  2.63109760e+01  1.13262199e+02]]

 [[ 8.84146333e-01  5.48780501e-01  3.04878056e-02]
  [ 9.14634168e-01  7.62195110e-01 -3.04878056e-02]
  [ 9.45122004e-01  7.92682946e-01 -3.04878056e-02]
  ...
  [-2.32317085e+01  4.23780489e+00 -3.90243912e+00]
  [-4.93902445e+00  5.70121956e+00  7.31707335e-01]
  [ 2.24390259e+01  9.66463470e+00  3.90243912e+00]]

 ...

 [[ 3.80182953e+01  1.98170733e+00

OPTIONAL STEP: PRE-PROCESSING TECHNIQUE (NORMALIZATION)

In [45]:
#APPLYING NORMALIZATION TO TRAINING AND TEST DATA SET

#TRAINING

norm_train_Acc = normalize(train_accelerometer)
norm_train_Grav = normalize(train_gravity)
norm_train_Gyro = normalize(train_gyroscope)
norm_train_Jins_Acc = normalize(train_jinsaccelerometer)
norm_train_Jins_Gyro = normalize(train_jinsgyroscope)
norm_train_Linear_Acc = normalize(train_linearacceleration)
norm_train_Mag = normalize(train_magnetometer)
norm_train_MS_Acc = normalize(train_msaccelerometer)
norm_train_MS_Gyro = normalize(train_msgyroscope)

#TESTING
norm_test_Acc = normalize(test_accelerometer)
norm_test_Grav = normalize(test_gravity)
norm_test_Gyro = normalize(test_gyroscope)
norm_test_Jins_Acc = normalize(test_jinsaccelerometer)
norm_test_Jins_Gyro = normalize(test_jinsgyroscope)
norm_test_Linear_Acc = normalize(test_linearacceleration)
norm_test_Mag = normalize(test_magnetometer)
norm_test_MS_Acc = normalize(test_msaccelerometer)
norm_test_MS_Gyro = normalize(test_msgyroscope)

STEP: FEATURE EXTRACTION

In [46]:
#2284x18x3 => 87x30-----IN 2D ARRAY

def extractFeatures(data_set):
    featuredArray = np.zeros((data_set.shape[0], 12, 3))
    data_set = data_set.astype('float32')
    for k in range(data_set.shape[0]):
      for i in range(3):
        mean = np.mean(data_set[k,:,i])           
        std = np.std(data_set[k,:,i])              
        min= np.min(data_set[k,:,i])
        max= np.max(data_set[k,:,i])
        channel_range = max-min
        median = np.median(data_set[k,:,i])
        mode, count = np.unique(data_set[k,:,i], return_counts=True)
        first_mode = mode[np.argmax(count)]
        variance = np.var(data_set[k,:,i])
        skewness = float(np.mean((data_set[k,:,i] - np.mean(data_set[k,:,i]))**3)/((np.std(data_set[k,:,i]) + 1e-7)**3))
        kurt = float(np.mean((data_set[k,:,i] - np.mean(data_set[k,:,i]))**4)/((np.std(data_set[k,:,i])**4)+ 1e-7) - 3)
        energy = np.sum(data_set[k,:,i]**2)
        dissimilarity = np.mean(np.abs(data_set[k,:,i] - mean))
        featuredArray[k,:,i] = [mean,std,min,max,channel_range,median,first_mode,variance,skewness,kurt,energy,dissimilarity]
    return featuredArray

EXTRACING FEATURES FOR BOTH TRAINING AND TESTING FILES SEPRATELY.

In [47]:
#TRAINING
features_train_Acc = extractFeatures(norm_train_Acc)
features_train_Grav = extractFeatures(norm_train_Grav)
features_train_Gyro = extractFeatures(norm_train_Gyro)
features_train_Jins_Acc = extractFeatures(norm_train_Jins_Acc)
features_train_Jins_Gyro = extractFeatures(norm_train_Jins_Gyro)
features_train_Linear_Acc = extractFeatures(norm_train_Linear_Acc)
features_train_Mag = extractFeatures(norm_train_Mag)
features_train_MS_Acc = extractFeatures(norm_train_MS_Acc)
features_train_MS_Gyro = extractFeatures(norm_train_MS_Gyro)
#TESTING
features_test_Acc = extractFeatures(norm_test_Acc)
features_test_Grav = extractFeatures(norm_test_Grav)
features_test_Gyro = extractFeatures(norm_test_Gyro)
features_test_Jins_Acc = extractFeatures(norm_test_Jins_Acc)
features_test_Jins_Gyro = extractFeatures(norm_test_Jins_Gyro)
features_test_Linear_Acc = extractFeatures(norm_test_Linear_Acc)
features_test_Mag = extractFeatures(norm_test_Mag)
features_test_MS_Acc = extractFeatures(norm_test_MS_Acc)
features_test_MS_Gyro = extractFeatures(norm_test_MS_Gyro)

In [48]:
print(features_train_Acc.shape)
print(features_train_Grav.shape)
print(features_train_Gyro.shape)
print(features_train_Jins_Acc.shape)
print(features_train_Jins_Gyro.shape)
print(features_train_Linear_Acc.shape)
print(features_train_MS_Acc.shape)
print(features_train_Mag.shape)
print(features_train_MS_Gyro.shape)

print(features_test_Acc.shape)
print(features_test_Grav.shape)
print(features_test_Gyro.shape)
print(features_test_Jins_Acc.shape)
print(features_test_Jins_Gyro.shape)
print(features_test_Linear_Acc.shape)
print(features_test_MS_Acc.shape)
print(features_test_Mag.shape)
print(features_test_MS_Gyro.shape)

(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2284, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)
(2288, 12, 3)


In [49]:
print(features_train_Grav)
print(features_train_Grav.shape)

[[[-9.53674331e-08  1.35421749e-06 -5.72204577e-08]
  [ 9.99999821e-01  9.99999404e-01  9.99999881e-01]
  [-1.73748350e+00 -2.42434239e+00 -1.91934788e+00]
  ...
  [-1.21438656e+00 -6.06710451e-01 -1.05201922e+00]
  [ 7.99999695e+02  7.99999084e+02  7.99999939e+02]
  [ 8.54679644e-01  8.53903949e-01  8.66910100e-01]]

 [[-9.53674295e-09  1.43051147e-06  7.62939436e-08]
  [ 9.99999821e-01  9.99999166e-01  9.99999821e-01]
  [-2.29968333e+00 -2.64853668e+00 -2.01668215e+00]
  ...
  [-6.49768814e-01  2.24255988e-01 -1.02455792e+00]
  [ 7.99999695e+02  7.99998718e+02  7.99999878e+02]
  [ 8.17275286e-01  8.37260008e-01  8.71921241e-01]]

 [[ 7.62939436e-08  1.69754026e-06  2.82669062e-05]
  [ 9.99999702e-01  9.99997973e-01  9.99993205e-01]
  [-2.24901199e+00 -8.95352900e-01 -9.66382682e-01]
  ...
  [ 6.15565672e-01  1.66216911e+00  1.74981391e+00]
  [ 7.99999390e+02  7.99996643e+02  7.99989075e+02]
  [ 7.90977001e-01  6.98534846e-01  6.88058615e-01]]

 ...

 [[ 3.81469718e-08  7.62939464e-07

Step: RE-SHAPING 

In [86]:
size_of_b=features_train_Acc.shape[1]*features_train_Acc.shape[2]

In [87]:
train_Acc = features_train_Acc.reshape(2284, size_of_b)         
train_Grav = features_train_Grav.reshape(2284,size_of_b)
train_Gyro = features_train_Gyro.reshape(2284,size_of_b)
train_Jins_Acc = features_train_Jins_Acc.reshape(2284,size_of_b)
train_Jins_Gyro = features_train_Jins_Gyro.reshape(2284,size_of_b)
train_Linear_Acc = features_train_Linear_Acc.reshape(2284,size_of_b)
train_MS_Acc = features_train_MS_Acc.reshape(2284,size_of_b)
train_Mag = features_train_Mag.reshape(2284,size_of_b)
train_MS_Gyro = features_train_MS_Gyro.reshape(2284,size_of_b)

test_Acc = features_test_Acc.reshape(2288, size_of_b)        
test_Grav = features_test_Grav.reshape(2288,size_of_b)
test_Gyro = features_test_Gyro.reshape(2288,size_of_b)
test_Jins_Acc = features_test_Jins_Acc.reshape(2288,size_of_b)
test_Jins_Gyro = features_test_Jins_Gyro.reshape(2288,size_of_b)
test_Linear_Acc = features_test_Linear_Acc.reshape(2288,size_of_b)
test_MS_Acc = features_test_MS_Acc.reshape(2288,size_of_b)
test_Mag = features_test_Mag.reshape(2288,size_of_b)
test_MS_Gyro = features_test_MS_Gyro.reshape(2288,size_of_b)

In [52]:
print(train_Acc)

[[-1.90734859e-08 -5.38825986e-07 -1.90734859e-08 ...  8.31634581e-01
   6.22655213e-01  7.50476003e-01]
 [ 9.53674295e-09  2.98023224e-07 -1.90734859e-08 ...  7.94367731e-01
   6.41088188e-01  7.90437996e-01]
 [ 3.81469718e-08 -4.30345523e-07  3.54290000e-06 ...  7.58214355e-01
   7.63774693e-01  7.82240450e-01]
 ...
 [ 0.00000000e+00  8.58306919e-08  3.81469718e-08 ...  8.67835104e-01
   6.40955687e-01  7.88789928e-01]
 [-2.72750844e-06 -2.08854681e-06  3.81469718e-08 ...  7.81304955e-01
   7.83999383e-01  7.89975226e-01]
 [-3.05175774e-07 -1.90734863e-06  1.77502636e-06 ...  7.89063215e-01
   8.00030947e-01  7.90963769e-01]]


OPTIONAL STEP: Applying feature selection Method

In [88]:
def extractWindowFeatures(data_set):
    featuredArray = np.zeros((data_set.shape[0]))
    data_set = data_set.astype('float32')
    mean = np.mean(data_set[:])           
    std = np.std(data_set[:])             
    min= np.min(data_set[:])
    max= np.max(data_set[:])
    mode, count = np.unique(data_set[:], return_counts=True)
    first_mode = mode[np.argmax(count)]
    variance = np.var(data_set[:])
    energy = np.sum(data_set[:]**2)
    dissimilarity = np.mean(np.abs(data_set[:] - mean))
    channel_range = max-min
    median = np.median(data_set[:])
    featuredArray = [mean,std,min,max,channel_range,median,first_mode]
    return np.array(featuredArray)

CALCULATING SLIDING WINDOW FEATURES 

In [54]:
#ASSUME
window_size=12
stride_size=3
window_features=36
def sliding_window_features(data_set, window_size, strideSize, one_win_feature):
    samples = data_set.shape[0]                
    num_features = data_set.shape[1]             
    print("all features:",num_features)
    num_windows = int(((num_features - window_size) / strideSize) + 1)        
    print("no of windows:",num_windows)
    new_data = np.zeros((samples, num_windows, one_win_feature))     
    for j in range(samples):
        for i in range(num_windows):    
            start = i * strideSize
            end = start + window_size
            window = data_set[j, start:end]
            features = extractWindowFeatures(window)
            new_data[j, i,:] = np.array(features)
    return new_data

In [55]:
window_size=13
stride_size=9
window_features=7

updated_train_Acc = sliding_window_features(train_Acc,window_size,stride_size,window_features)
updated_train_Grav = sliding_window_features(train_Grav,window_size,stride_size,window_features)
updated_train_Gyro = sliding_window_features(train_Gyro,window_size,stride_size,window_features)
updated_train_Jins_Acc = sliding_window_features(train_Jins_Acc,window_size,stride_size,window_features)
updated_train_Jins_Gyro = sliding_window_features(train_Jins_Gyro,window_size,stride_size,window_features)
updated_train_Linear_Acc = sliding_window_features(train_Linear_Acc,window_size,stride_size,window_features)
updated_train_MS_Acc = sliding_window_features(train_MS_Acc,window_size,stride_size,window_features)
updated_train_Mag = sliding_window_features(train_Mag,window_size,stride_size,window_features)
updated_train_MS_Gyro = sliding_window_features(train_MS_Gyro,window_size,stride_size,window_features)

updated_test_Acc = sliding_window_features(test_Acc,window_size,stride_size,window_features)
updated_test_Grav = sliding_window_features(test_Grav,window_size,stride_size,window_features)
updated_test_Gyro = sliding_window_features(test_Gyro,window_size,stride_size,window_features)
updated_test_Jins_Acc = sliding_window_features(test_Jins_Acc,window_size,stride_size,window_features)
updated_test_Jins_Gyro = sliding_window_features(test_Jins_Gyro,window_size,stride_size,window_features)
updated_test_Linear_Acc = sliding_window_features(test_Linear_Acc,window_size,stride_size,window_features)
updated_test_MS_Acc = sliding_window_features(test_MS_Acc,window_size,stride_size,window_features)
updated_test_Mag = sliding_window_features(test_Mag,window_size,stride_size,window_features)
updated_test_MS_Gyro = sliding_window_features(test_MS_Gyro,window_size,stride_size,window_features)



all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3
all features: 36
no of windows: 3


PRINTING THE UPDATED SHAPES WE GOT

In [57]:
print(updated_train_Acc.shape)
print(updated_train_Grav.shape)
print(updated_train_Gyro.shape)
print(updated_train_Jins_Acc.shape)
print(updated_train_Jins_Gyro.shape)
print(updated_train_Linear_Acc.shape)
print(updated_train_MS_Acc.shape)
print(updated_train_Mag.shape)
print(updated_train_MS_Gyro.shape)


(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)
(2284, 3, 7)


FINDIND THE LEARNED DATA BY RESHAPING

In [62]:

rows = updated_train_Acc.shape[0]
rows1 = updated_test_Acc.shape[0]
cols = updated_train_Acc.shape[1] * updated_train_Acc.shape[2]
learned_train_Acc = updated_train_Acc.reshape(rows,cols)
learned_train_Grav = updated_train_Grav.reshape(rows,cols)
learned_train_Gyro = updated_train_Gyro.reshape(rows,cols)
learned_train_Jins_Acc = updated_train_Jins_Acc.reshape(rows,cols)
learned_train_Jins_Gyro = updated_train_Jins_Gyro.reshape(rows,cols)
learned_train_Linear_Acc = updated_train_Linear_Acc.reshape(rows,cols)
learned_train_MS_Acc = updated_train_MS_Acc.reshape(rows,cols)
learned_train_Mag = updated_train_Mag.reshape(rows,cols)
learned_train_MS_Gyro = updated_train_MS_Gyro.reshape(rows,cols)

learned_test_Acc = updated_test_Acc.reshape(rows1,cols)
learned_test_Grav = updated_test_Grav.reshape(rows1,cols)
learned_test_Gyro = updated_test_Gyro.reshape(rows1,cols)
learned_test_Jins_Acc = updated_test_Jins_Acc.reshape(rows1,cols)
learned_test_Jins_Gyro = updated_test_Jins_Gyro.reshape(rows1,cols)
learned_test_Linear_Acc = updated_test_Linear_Acc.reshape(rows1,cols)
learned_test_MS_Acc = updated_test_MS_Acc.reshape(rows1,cols)
learned_test_Mag = updated_test_Mag.reshape(rows1,cols)
learned_test_MS_Gyro = updated_test_MS_Gyro.reshape(rows1,cols)


In [63]:
print(learned_train_Acc.shape)
print(learned_train_Grav.shape)
print(learned_train_Gyro.shape)
print(learned_train_Jins_Acc.shape)
print(learned_train_Jins_Gyro.shape)
print(learned_train_Linear_Acc.shape)
print(learned_train_MS_Acc.shape)
print(learned_train_Mag.shape)
print(learned_train_MS_Gyro.shape)


(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)
(2284, 21)


STEP: PERFORMING CONCATENNATION

In [65]:
trainingExamples = np.concatenate([learned_train_Acc, learned_train_Grav, learned_train_Gyro, learned_train_Jins_Acc, learned_train_Jins_Gyro, learned_train_Linear_Acc, learned_train_MS_Acc, learned_train_Mag, learned_train_MS_Gyro], axis=1)
testingExamples = np.concatenate([learned_test_Acc, learned_test_Grav, learned_test_Gyro, learned_test_Jins_Acc, learned_test_Jins_Gyro, learned_test_Linear_Acc, learned_test_MS_Acc, learned_test_Mag, learned_test_MS_Gyro], axis=1)

In [66]:
print(trainingExamples.shape)
print(testingExamples.shape)

print(train_labels.shape)
print(test_labels.shape)

(2284, 189)
(2288, 189)
(2284,)
(2288,)


In [67]:
print(trainingExamples)  #total 324 feature total 2284 examples. 

[[ 8.29787493e-01  2.87281442e+00 -3.62664533e+00 ...  2.69586151e+02
   3.27868462e-01  1.00000000e+00]
 [ 6.95499361e-01  2.64112425e+00 -3.25087380e+00 ...  2.69227448e+02
   4.28280711e-01  1.00000000e+00]
 [ 6.63221776e-01  2.70941973e+00 -3.90126562e+00 ...  2.68779938e+02
   7.10507035e-01  1.00000000e+00]
 ...
 [ 7.93749273e-01  2.43423414e+00 -2.96235919e+00 ...  2.69514160e+02
   2.66579598e-01  1.00000000e+00]
 [ 7.56847739e-01  2.95578241e+00 -3.66438007e+00 ...  2.69016327e+02
   1.00000000e+00  1.00000000e+00]
 [ 8.10972571e-01  2.85884905e+00 -3.26940370e+00 ...  2.68200317e+02
   1.00000000e+00  1.00000000e+00]]


In [68]:
print(testingExamples)

[[ 4.96101528e-01  2.09459519e+00 -3.54206991e+00 ...  2.69446869e+02
   9.99999881e-01  1.00000000e+00]
 [ 7.30624139e-01  2.96939731e+00 -4.37171412e+00 ...  2.69857452e+02
   4.66041803e-01  1.00000000e+00]
 [ 5.56988776e-01  2.42999840e+00 -3.16152024e+00 ...  2.69088531e+02
   1.00000000e+00  1.00000000e+00]
 ...
 [ 8.35240722e-01  2.81676745e+00 -3.68504286e+00 ...  2.69994171e+02
   9.99999881e-01  1.00000000e+00]
 [ 3.77928227e-01  3.48795199e+00 -5.63139391e+00 ...  2.70991028e+02
   9.99999881e-01  1.00000012e+00]
 [ 6.61452234e-01  2.81899571e+00 -3.88171077e+00 ...  2.68493134e+02
   2.28938386e-01  1.00000000e+00]]


STEP: PERFORMING SVM

In [77]:
from sklearn import svm

clf = svm.SVC(C=1, gamma='auto')
clf.fit(trainingExamples, train_labels)


SVC(C=1, gamma='auto')

In [78]:
y_pred = clf.predict(testingExamples)

In [79]:
print(y_pred)

[17 45 24 ... 50 21 28]


STEP: Using evaluation methods like confusion matrix, accuracy, Average F1 score etc.

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
confusion = confusion_matrix(test_labels, y_pred)
print('*************RESULTS FOR SVM************************')


accuracy = accuracy_score(test_labels,y_pred)
weightedF1 = f1_score(test_labels,y_pred,average='weighted')
averageF1 = f1_score(test_labels,y_pred,average='macro')
allF1Scores = f1_score(test_labels,y_pred,average=None)
confuse_matrix = confusion_matrix(test_labels,y_pred)


# Print results
print('   C = 1.0 ')
print('   Average F1-score = %.4f' % (averageF1))
print('   Test accuracy = %.2f %%' % (accuracy*100))
print('   Weighted F1-score = %.4f' % (weightedF1))
print('   All F1-scores:')
print(allF1Scores)
print('   Confusion Matrix:')
print(confuse_matrix)


print('-------------------------------------------------------')

*************RESULTS FOR SVM************************
   C = 1.0 
   Average F1-score = 0.2168
   Test accuracy = 22.90 %
   Weighted F1-score = 0.2211
   All F1-scores:
[0.63829787 0.32142857 0.21505376 0.21276596 0.19672131 0.08791209
 0.04938272 0.06382979 0.1369863  0.         0.19753086 0.23076923
 0.78873239 0.1971831  0.30769231 0.52941176 0.17142857 0.44444444
 0.16438356 0.07692308 0.08247423 0.06593407 0.02898551 0.22680412
 0.12844037 0.12903226 0.19753086 0.10169492 0.175      0.175
 0.21276596 0.20779221 0.03571429 0.33333333 0.10434783 0.12307692
 0.4        0.08333333 0.23404255 0.48351648 0.4556962  0.53521127
 0.4047619  0.20895522 0.16393443 0.08       0.05263158 0.06779661
 0.27350427 0.15189873 0.08247423 0.32876712 0.15       0.27027027
 0.14084507]
   Confusion Matrix:
[[30  2  1 ...  0  0  0]
 [ 1 18  8 ...  0  2  0]
 [ 3  7 10 ...  0  0  0]
 ...
 [ 1  1  0 ...  6  0  0]
 [ 0  0  2 ...  0 10  0]
 [ 0  0  0 ...  0  0  5]]
-------------------------------------------

In [49]:
y_pred = clf.predict(trainingExamples)
train_accuracy = accuracy_score(train_labels,y_pred)
print(train_accuracy)

0.6492994746059545


OPTIONAL STEP : Another multi-class classification method for comparisoN

PERFORMING LOGISTIC REGRESSION FOR COMPARISON

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

# Scale the data
scaler = StandardScaler()
scaled_trainingExamples = scaler.fit_transform(trainingExamples)
scaled_testingExamples = scaler.transform(testingExamples)

# Create logistic regression classifier with increased max_iter, regularization, and a different solver
clf = LogisticRegression(max_iter=2284, solver='saga', penalty='l2', C=1.0)
clf.fit(scaled_trainingExamples, train_labels)
y_pred = clf.predict(scaled_testingExamples)

# Compute evaluation metrics
confusion = confusion_matrix(test_labels, y_pred)
accuracy = accuracy_score(test_labels, y_pred)
weightedF1 = f1_score(test_labels, y_pred, average='weighted')
averageF1 = f1_score(test_labels, y_pred, average='macro')
allF1Scores = f1_score(test_labels, y_pred, average=None)

# Print results
print('Logistic Regression Results:')
print('   Average F1-score = %.4f' % averageF1)
print('   Test accuracy = %.2f %%' % (accuracy * 100))
print('   Weighted F1-score = %.4f' % weightedF1)
print('   All F1-scores:')
print(allF1Scores)
print('   Confusion Matrix:')
print(confusion)
print('-------------------------------------------------------')


Logistic Regression Results:
   Average F1-score = 0.3029
   Test accuracy = 30.38 %
   Weighted F1-score = 0.3032
   All F1-scores:
[0.61333333 0.34951456 0.28282828 0.22680412 0.2        0.13513514
 0.13953488 0.26804124 0.12121212 0.2173913  0.175      0.27956989
 0.88607595 0.32608696 0.38095238 0.68817204 0.41558442 0.55319149
 0.15909091 0.25       0.18181818 0.18947368 0.14084507 0.37333333
 0.17204301 0.34146341 0.26804124 0.02380952 0.23376623 0.1627907
 0.2        0.1971831  0.24324324 0.36781609 0.15909091 0.24096386
 0.41463415 0.28571429 0.45238095 0.66666667 0.69879518 0.69767442
 0.37837838 0.20895522 0.27586207 0.1627907  0.12765957 0.10810811
 0.22222222 0.30588235 0.29545455 0.46511628 0.17391304 0.35616438
 0.1978022 ]
   Confusion Matrix:
[[23  4  2 ...  0  2  0]
 [ 1 18  8 ...  1  0  0]
 [ 0  5 14 ...  0  2  0]
 ...
 [ 0  1  0 ...  8  0  0]
 [ 0  0  1 ...  0 13  0]
 [ 0  0  0 ...  0  0  9]]
-------------------------------------------------------


STEP: EXPERIMENTS WITH C-VALUE AND KERNALS:

APPLY GAUSSAIN KERNAL and C=0.00005

In [83]:
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
clf = svm.SVC(C=0.00005, kernel='rbf', gamma='auto')
clf.fit(trainingExamples, train_labels)
y_pred = clf.predict(testingExamples)

confusion = confusion_matrix(test_labels, y_pred)
print('*************RESULTS FOR SVM with Gassuain kernal and C=0.00005    ************************')


accuracy = accuracy_score(test_labels,y_pred)
weightedF1 = f1_score(test_labels,y_pred,average='weighted')
averageF1 = f1_score(test_labels,y_pred,average='macro')
allF1Scores = f1_score(test_labels,y_pred,average=None)
confuse_matrix = confusion_matrix(test_labels,y_pred)


# Print results
print('   C = 0.00005 ')
print('   Average F1-score = %.4f' % (averageF1))
print('   Test accuracy = %.2f %%' % (accuracy*100))
print('   Weighted F1-score = %.4f' % (weightedF1))
print('   All F1-scores:')
print(allF1Scores)
print('   Confusion Matrix:')
print(confuse_matrix)


print('-------------------------------------------------------')

*************RESULTS FOR SVM with Gassuain kernal and C=0.00005    ************************
   C = 0.00005 
   Average F1-score = 0.0022
   Test accuracy = 3.15 %
   Weighted F1-score = 0.0023
   All F1-scores:
[0.         0.         0.         0.         0.06373816 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.05761317 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]
   Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
-------------------------------------------------------


EXPERIMENT-02

APPLY GAUSSAIN KERNAL and C=100000

In [84]:
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
clf = svm.SVC(C=100000, kernel='rbf', gamma='auto')
clf.fit(trainingExamples, train_labels)
y_pred = clf.predict(testingExamples)

confusion = confusion_matrix(test_labels, y_pred)
print('*************RESULTS FOR SVM with Gassuain kernal and C=100000    ************************')


accuracy = accuracy_score(test_labels,y_pred)
weightedF1 = f1_score(test_labels,y_pred,average='weighted')
averageF1 = f1_score(test_labels,y_pred,average='macro')
allF1Scores = f1_score(test_labels,y_pred,average=None)
confuse_matrix = confusion_matrix(test_labels,y_pred)


# Print results
print('   C = 100000 ')
print('   Average F1-score = %.4f' % (averageF1))
print('   Test accuracy = %.2f %%' % (accuracy*100))
print('   Weighted F1-score = %.4f' % (weightedF1))
print('   All F1-scores:')
print(allF1Scores)
print('   Confusion Matrix:')
print(confuse_matrix)


print('-------------------------------------------------------')

*************RESULTS FOR SVM with Gassuain kernal and C=100000    ************************
   C = 100000 
   Average F1-score = 0.2410
   Test accuracy = 24.78 %
   Weighted F1-score = 0.2438
   All F1-scores:
[0.59574468 0.34782609 0.20930233 0.24489796 0.24299065 0.12195122
 0.02469136 0.06451613 0.09756098 0.16666667 0.14457831 0.27956989
 0.84507042 0.22222222 0.38554217 0.52525253 0.21212121 0.49484536
 0.15384615 0.10958904 0.08108108 0.11494253 0.08955224 0.21590909
 0.14634146 0.12121212 0.19469027 0.13333333 0.15       0.12765957
 0.32258065 0.26666667 0.09375    0.46938776 0.09756098 0.10810811
 0.43298969 0.08571429 0.32608696 0.53333333 0.49350649 0.54054054
 0.27027027 0.21212121 0.26315789 0.05714286 0.13333333 0.12820513
 0.29545455 0.17721519 0.1025641  0.41975309 0.10810811 0.36923077
 0.08219178]
   Confusion Matrix:
[[28  2  1 ...  0  0  0]
 [ 1 20  9 ...  0  2  0]
 [ 3 11  9 ...  0  0  0]
 ...
 [ 0  2  0 ...  4  0  1]
 [ 0  0  2 ...  0 12  0]
 [ 0  0  0 ...  0  0  3